name: Generate Half-Year GitHub Activity Calendar

on:
  schedule:
    - cron: "0 0 * * 0" # Chaque dimanche Ã  minuit
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  half_year_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar.duration: full-year

